[build]
  command = "npm run build:client"
  publish = "client/dist/spa"   # or "dist/spa" if your Vite build actually outputs spa folder

[build.environment]
  NODE_VERSION = "20.19.0"

# For React Router SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
