[build]
  command = "npm ci && npm run build:client"
  publish = "dist"   # or "dist/spa" if your Vite build actually outputs spa folder

[build.environment]
  NODE_VERSION = "20.5.0"

# For React Router SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
